{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kargo-argocd-observer.serviceAccountName" . }}
  labels:
    {{- include "kargo-argocd-observer.labels" . | nindent 4 }}
{{- end }}
