apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kargo-argocd-observer
  namespace: kargo-observer
  labels:
    app.kubernetes.io/name: kargo-argocd-observer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kargo-argocd-observer
  endpoints:
    - port: metrics
      interval: 30s
